/* eslint-env node */
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const LOG_DIR = path.join(ROOT, 'logs');

module.exports = {
  apps: [
    // ─── Web app (Vite dev server) ──────────────────────────────
    {
      name: 'web-app',
      cwd: ROOT,
      script: 'cmd.exe',
      args: '/c npx.cmd --workspace=@argentinaradar/web vite --host',
      interpreter: 'none',
      windowsHide: true,
      env: { NODE_ENV: 'development' },
      watch: false,
      max_memory_restart: '500M',
      error_file: path.join(LOG_DIR, 'web-error.log'),
      out_file: path.join(LOG_DIR, 'web-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },

    // ─── News ingestion ─────────────────────────────────────────
    {
      name: 'news-ingestion',
      cwd: ROOT,
      script: 'cmd.exe',
      args: '/c node --loader ts-node/esm services/news-ingestion/src/index.ts',
      interpreter: 'none',
      windowsHide: true,
      env: {
        NODE_ENV: 'development',
        PORT: '3001',
        INGESTION_INTERVAL: '300000',
      },
      watch: ['services/news-ingestion/src', 'shared/types', 'data/sources.json'],
      max_memory_restart: '500M',
      error_file: path.join(LOG_DIR, 'news-ingestion-error.log'),
      out_file: path.join(LOG_DIR, 'news-ingestion-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },

    // ─── Geolocation ────────────────────────────────────────────
    {
      name: 'geolocation',
      cwd: ROOT,
      script: 'cmd.exe',
      args: '/c node --loader ts-node/esm services/geolocation/src/server.ts',
      interpreter: 'none',
      windowsHide: true,
      env: {
        NODE_ENV: 'development',
        PORT: '3002',
        NEWS_SERVICE_URL: 'http://localhost:3001',
        POLL_INTERVAL: '30000',
      },
      watch: ['services/geolocation/src', 'shared/gazetteer', 'shared/types'],
      max_memory_restart: '500M',
      error_file: path.join(LOG_DIR, 'geolocation-error.log'),
      out_file: path.join(LOG_DIR, 'geolocation-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },

    // ─── Twitter Publisher (Node.js / Express)  ─────────────────
    {
      name: 'twitter-publisher',
      cwd: ROOT,
      script: 'cmd.exe',
      args: '/c node --loader ts-node/esm services/twitter-publisher/src/index.ts',
      interpreter: 'none',
      windowsHide: true,
      env: {
        NODE_ENV: 'development',
        PORT: '3004',
        AI_PROCESSOR_URL: 'http://localhost:3013',
        POLL_INTERVAL: '300000',
      },
      watch: ['services/twitter-publisher/src', 'shared/types'],
      max_memory_restart: '500M',
      error_file: path.join(LOG_DIR, 'twitter-publisher-error.log'),
      out_file: path.join(LOG_DIR, 'twitter-publisher-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },

    // ─── Hermes Bridge (Python / FastAPI) ───────────────────────
    {
      name: 'hermes-bridge',
      cwd: path.join(ROOT, 'services', 'hermes-bridge'),
      script: 'cmd.exe',
      args: '/c python -m uvicorn src.server:app --host 0.0.0.0 --port 3005',
      interpreter: 'none',
      windowsHide: true,
      env: {
        NODE_ENV: 'development',
        PORT: '3005',
        PYTHONPATH: '.',
        DB_PATH: path.join(ROOT, 'data', 'argentina-radar.db'),
        TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID ?? '',
        TWITTER_PUBLISHER_URL: 'http://localhost:3004',
        EVENT_DETECTOR_URL: 'http://localhost:3008',
        APPROVAL_POLL_INTERVAL: '5',
        APPROVAL_EVENT_POLL_INTERVAL: '60',
        APPROVAL_AUTO_PUBLISH_THRESHOLD: '70',
      },
      watch: ['src'],
      max_memory_restart: '500M',
      error_file: path.join(LOG_DIR, 'hermes-bridge-error.log'),
      out_file: path.join(LOG_DIR, 'hermes-bridge-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },

    // ─── Economic Data (Node.js / Express) ──────────────────────
    {
      name: 'economic-data',
      cwd: ROOT,
      script: 'cmd.exe',
      args: '/c node --loader ts-node/esm services/economic-data/src/server.ts',
      interpreter: 'none',
      windowsHide: true,
      env: {
        NODE_ENV: 'development',
        PORT: '3006',
        DB_PATH: path.join(ROOT, 'data', 'argentina-radar.db'),
        HERMES_ALERT_URL: 'http://localhost:3005/api/alerts',
      },
      watch: ['services/economic-data/src', 'shared/types'],
      max_memory_restart: '500M',
      error_file: path.join(LOG_DIR, 'economic-data-error.log'),
      out_file: path.join(LOG_DIR, 'economic-data-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },

    // ─── Alerts Service (Node.js / Express) — PR 7 ──────────────
    {
      name: 'alerts',
      cwd: ROOT,
      script: 'cmd.exe',
      args: '/c node --loader ts-node/esm services/alerts/src/server.ts',
      interpreter: 'none',
      windowsHide: true,
      env: {
        NODE_ENV: 'development',
        PORT: '3007',
      },
      watch: ['services/alerts/src', 'shared/types'],
      max_memory_restart: '500M',
      error_file: path.join(LOG_DIR, 'alerts-error.log'),
      out_file: path.join(LOG_DIR, 'alerts-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    // ─── Event Detector (Node.js / Express) — PR 2.2 ────────────
    {
      name: 'event-detector',
      cwd: ROOT,
      script: 'cmd.exe',
      args: '/c node --loader ts-node/esm services/event-detector/src/server.ts',
      interpreter: 'none',
      windowsHide: true,
      env: {
        NODE_ENV: 'development',
        PORT: '3008',
        AI_PROCESSOR_URL: 'http://localhost:3013',
      },
      watch: ['services/event-detector/src', 'shared/types'],
      max_memory_restart: '500M',
      error_file: path.join(LOG_DIR, 'event-detector-error.log'),
      out_file: path.join(LOG_DIR, 'event-detector-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },

    // ─── AI Processor (Python / FastAPI) — PR 2.1 ────────────────
    {
      name: 'ai-processor',
      cwd: path.join(ROOT, 'services', 'ai-processor'),
      script: 'cmd.exe',
      args: '/c python -m uvicorn src.server:app --host 0.0.0.0 --port 3013',
      interpreter: 'none',
      windowsHide: true,
      env: {
        NODE_ENV: 'development',
        PORT: '3013',
        PYTHONPATH: '.',
        DAILY_BUDGET: '2.00',
        AI_PROVIDER: 'openai',
      },
      watch: ['src'],
      max_memory_restart: '500M',
      error_file: path.join(LOG_DIR, 'ai-processor-error.log'),
      out_file: path.join(LOG_DIR, 'ai-processor-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    // ─── Night Owl (Node.js / Express) — Fase 1 ───────────────────
    {
      name: 'night-owl',
      cwd: ROOT,
      script: 'cmd.exe',
      args: '/c node --loader ts-node/esm services/night-owl/src/server.ts',
      interpreter: 'none',
      windowsHide: true,
      env: {
        NODE_ENV: 'development',
        PORT: '3011',
        NIGHT_OWL_ENABLED: 'true',
        NIGHT_OWL_BUDGET_PER_NIGHT: '1.00',
        TIMEZONE: 'America/Argentina/Buenos_Aires',
      },
      watch: ['services/night-owl/src', 'shared/types'],
      max_memory_restart: '500M',
      error_file: path.join(LOG_DIR, 'night-owl-error.log'),
      out_file: path.join(LOG_DIR, 'night-owl-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },

    // ─── Auth Service (Node.js / Express) — Fase 1 Roles ────────
    {
      name: 'auth',
      cwd: ROOT,
      script: 'cmd.exe',
      args: '/c node --loader ts-node/esm services/auth/src/index.ts',
      interpreter: 'none',
      windowsHide: true,
      env: {
        NODE_ENV: 'development',
        PORT: '3010',
        JWT_SECRET: 'dev-jwt-secret-change-in-production',
        JWT_EXPIRES_IN: '15m',
        REFRESH_TOKEN_EXPIRES_IN: '7d',
      },
      watch: ['services/auth/src', 'packages/auth-middleware/src', 'packages/database/src'],
      max_memory_restart: '500M',
      error_file: path.join(LOG_DIR, 'auth-error.log'),
      out_file: path.join(LOG_DIR, 'auth-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },

    // ─── Trend Analyzer (Node.js / Express) — PR 3.1 ─────────────
    {
      name: 'trend-analyzer',
      cwd: ROOT,
      script: 'cmd.exe',
      args: '/c node --loader ts-node/esm services/trend-analyzer/src/server.ts',
      interpreter: 'none',
      windowsHide: true,
      env: {
        NODE_ENV: 'development',
        PORT: '3009',
        ANALYSIS_INTERVAL: '1800000',
      },
      watch: ['services/trend-analyzer/src', 'shared/types'],
      max_memory_restart: '500M',
      error_file: path.join(LOG_DIR, 'trend-analyzer-error.log'),
      out_file: path.join(LOG_DIR, 'trend-analyzer-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },

    // ─── Admin Dashboard (Node.js / Express) — Fase 1 Dashboard ───
    {
      name: 'admin',
      cwd: ROOT,
      script: 'cmd.exe',
      args: '/c node --loader ts-node/esm services/admin/src/server.ts',
      interpreter: 'none',
      windowsHide: true,
      env: {
        NODE_ENV: 'development',
        ADMIN_PORT: '3012',
        JWT_SECRET: 'dev-jwt-secret-change-in-production',
        EVENT_DETECTOR_URL: 'http://localhost:3008',
        COLLECTOR_INTERVAL: '3600000',
      },
      watch: ['services/admin/src', 'packages/auth-middleware/src', 'packages/database/src'],
      max_memory_restart: '500M',
      error_file: path.join(LOG_DIR, 'admin-error.log'),
      out_file: path.join(LOG_DIR, 'admin-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
  ],
};
